Executar no terminal: 
```
gcloud auth print-access-token
```

In [27]:
# Criar credencial de acesso
import google.oauth2.credentials

credentials = google.oauth2.credentials.Credentials('CREDENCIAL ADQUIRIDA PELO TERMINAL')

In [28]:
# Instanciar cliente do BigQuery
from google.cloud import bigquery

client = bigquery.Client(credentials=credentials, project='white-script-238515')

In [29]:
# Realizar a query.
query = '''
    SELECT * FROM `white-script-238515.clean_seller.seller_bank_account` 
    LIMIT 100
'''
query_job = client.query(query)  # API request
dataframe = query_job.to_dataframe()

In [30]:
# Trabalhar com o Dataframe
dataframe

              cnpj  ...                       validation_name
0   37852441000121  ...         Transfeera - validação básica
1   37852441000121  ...  Transfeera - validação microdepósito
2   41363075000114  ...         Transfeera - validação básica
3   41363075000114  ...  Transfeera - validação microdepósito
4   40319426000127  ...         Transfeera - validação básica
..             ...  ...                                   ...
95  40979787000108  ...  Transfeera - validação microdepósito
96  40979787000108  ...         Transfeera - validação básica
97  40064411000165  ...         Transfeera - validação básica
98  40064411000165  ...  Transfeera - validação microdepósito
99  39279825000122  ...  Transfeera - validação microdepósito

[100 rows x 10 columns]